### ISSUE TITLE
Jello Distortion

### ISSUE THREAD

**Issue by NHodgesVFX** [SIsilicon/Godot-Planar-Reflection-Plugin#2]
I like the plugin so far. I noticed however when moving the camera the planar reflection doesn't move correctly and has a jello distortion to it. Keep up the great work! :)

https://streamable.com/amq7o

**Comment by SIsilicon** [comment]
Believe it it or not, that's actually expected behaviour. Because the editor's camera position gets updated after _all_ scripts it's hard to get the transform matching. This problem should only happen in the editor, but if you find that it also happens when running the game, try reducing the camera controlling script's _process priority_ (If you have a script).

**Comment by SIsilicon** [comment]
_But_, I think I might have an idea to get rid of it. :)
